apiVersion: v1
kind: Service
metadata:
  name: {{ include "releaseNameFormatted" . }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    release: {{ $.Release.Name }}
spec:
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    release: {{ $.Release.Name }}
